# apiVersion: v1
# kind: Service
# metadata:
#   name: react-app
#   labels:
#     app: react-app
# spec:
#   type: NodePort
#   selector:
#     app: react-app # Ensure this matches the label of your Deployment/Pod
#   ports:
#     - port: 80        # The port the service exposes to external clients
#       targetPort: 5173 # The port the Vite app listens on inside the container
#       nodePort: 30007 

apiVersion: v1
kind: Service
metadata:
  name: react-app
  labels:
    app: react-app
spec:
  ports:
  - port: 80
    targetPort: 5173
    protocol: TCP
  selector:
    app: react-app
  type: ClusterIP
